9 layout
dsc-project-mr/mr-fe-internal pull request #13
Opened 2022-11-12 19:12 UTC by CeereeC

Closes #9 .

**Overview of changes:**
- Used Mui Grid to create the Layout

**Anything you'd like to highlight/discuss:**
- Not sure how to enforce the gutter, for now I just used columnSpacing

2022-11-13 16:01 UTC, wilinetan requested changes
for the footer, it seems like the internal portal does not need one so can help to remove.

2022-12-01 09:04 UTC, CeereeC commented on components/Layout/index.tsx
> +          </Box>
For the gutters, I'm not sure how to enforce as well. Would it be a good idea to develop an overlay that shows the gutters and the pink rectangles like the image in Issue #9 ? The overlay can be toggled on and off and frontend engineers can use it as a reference, like say making sure the components align with the overlay rectangles.

2022-12-07 10:42 UTC, wilinetan commented on components/Layout/index.tsx
> +          </Box>
hmm, i think for now no need. cos gutters is the space between components so we won't know for sure what is an indiv component width and length also.

2022-12-11 14:31 UTC, wilinetan approved these changes

2022-12-11 14:31 UTC, merged