34 create new user account page internal
dsc-project-mr/mr-fe-internal pull request #40
Opened 2023-01-02 04:39 UTC by lihuicham

Closes #34

**Overview of changes:**
Added text fields for username, email and role. 

**Anything you'd like to highlight/discuss:**
Attempted to do image upload component for avatar (UploadProfileImage.tsx), however, failed to do so cos of typescript error. Need help to fix the ref errors and one onclick (button) error before I can test the functionality.

2023-01-04 07:19 UTC, wilinetan reviewed
when using refs, need to instantiate to null i think otherwise will get some error
`const usernameRef = React.useRef(null)`

for `UploadProfileImage.tsx`:
```
const inputFileRef = React.useRef<HTMLInputElement>(null)

const cleanUp = () => {
    URL.revokeObjectURL(image)
    if (inputFileRef.current) {
      inputFileRef.current.value = ''
    }
  }

const handleClick = (event: React.MouseEvent<HTMLButtonElement>) => {
    if (image) {
      event.preventDefault()
      setImage('')
    }
  }

```

2023-01-04 07:19 UTC, wilinetan commented on pages/_app.tsx
> +      <CreateNewUserAccount />
think i already mentioned this previously. you do not need to modify this file. ur work will be at the path of u specified in the pages folder. https://nextjs.org/docs/routing/introduction

2023-01-04 07:19 UTC, wilinetan commented on pages/CreateNewUserAccount/CreateNewUserAccount.tsx
> +import * as React from 'react';
this file should be at `pages/users/create.tsx`. The other helper components can put them in the components folder instead

2023-01-04 07:19 UTC, wilinetan commented on pages/CreateNewUserAccount/CreateNewUserAccount.tsx
> +                    <Typography>{usernameRef.current.value}</Typography>
whats this line for? was this for ur testing?

2023-01-25 09:56 UTC, wilinetan reviewed
I realised there are some "ugly" spaces and long lines. are u using prettier and vscode? if you are using vscode, can install the prettier extension to help with formatting the code

The pop up should have the actual user name and bolded
![Screen Shot 2023-01-25 at 5 45 32 PM](https://user-images.githubusercontent.com/51109678/214530780-980c89f7-95d0-41fb-8a87-43f76600b8b6.png)

2023-01-25 09:56 UTC, wilinetan commented on pages/users/index.tsx
> +import * as React from 'react';
move this file to `pages/users/create.tsx`

2023-01-25 09:56 UTC, wilinetan commented on pages/users/index.tsx
> +                <TextField id="outlined-basic" label="Email Address" variant="outlined" required/>
you will need to use the `onChange` prop if you are using it as a controlled component. or a `useRef` if u are using it as an uncontrolled component. Either way is fine just keep it consistent

2023-01-25 09:56 UTC, wilinetan commented on components/CreateNewUserAccount/CreateButton.tsx
> +            {"Create New User?"}
nit. you do not need the `{""}`
can just be `<DialogTitle id="alert-dialog-title" variant="h5">Create New User?</DialogTitle>

2023-01-25 09:56 UTC, wilinetan commented on components/CreateNewUserAccount/CreateButton.tsx
> +        </Button>
We should disable this button if any of the fields are blank since all fields should be required

2023-01-25 09:56 UTC, wilinetan commented on pages/users/index.tsx
> +import CreateButton from "../../components/CreateNewUserAccount/CreateButton";
```
import SelectRoleTextField from 'components/CreateNewUserAccount/SelectRoleTextField'
import UploadProfileImage from 'components/CreateNewUserAccount/UploadProfileImage'
import CreateButton from 'components/CreateNewUserAccount/CreateButton'
```

2023-02-14 12:52 UTC, lihuicham commented
![2023-02-14 20 45 32](https://user-images.githubusercontent.com/99931775/218742357-8cf7a52e-be49-4858-aef1-fad364d4661c.jpg)

Hey Wiline ! I resolved the comments you made and fixed the bugs in this branch. All components in this page are completed, except that I faced issues in writing (POST request) into the endpoint. 

I followed guan ming's one and use Axios for POST request (can refer [here](https://axios-http.com/docs/api_intro)), but I still get the error of `net::ERR_CONNECTION_REFUSED`, not sure why, would it be due to the server settings ? 

i'm using the postman collection dated at 010223 (as of today, it's the latest dominic has sent to the fe chat) 

please take a look at it and update me on the issue, thank you !

2023-02-14 16:32 UTC, wilinetan requested changes
think your prettier might still not be working?

2023-02-14 16:32 UTC, wilinetan commented on components/CreateNewUserAccount/CreateButton.tsx
> +        console.log(error);
can use the notistick snackbars for user feedback when success and error

2023-02-14 16:32 UTC, wilinetan commented on components/CreateNewUserAccount/SelectRoleTextField.tsx
> +                    <MenuItem value={'Internal User'}>Internal User</MenuItem>
values here are wrong. please refer to actual enums used in backend.
```
export enum Role {
  SUPER_ADMIN = 'super admin',
  DONATION_CAMPAIGN_EDITOR = 'donation campaign editor',
  ARTICLE_EDITOR = 'article editor',
  USER = 'internal user',
}
```

2023-02-14 16:32 UTC, wilinetan commented on components/CreateNewUserAccount/SelectRoleTextField.tsx
> +                    <MenuItem value={'Internal User'}>Internal User</MenuItem>
you can create an enum for roles as well

2023-02-15 14:28 UTC, wilinetan commented on components/CreateNewUserAccount/CreateButton.tsx
> +        console.log(error);
refer to this PR for how to use notistick in the PublishButton file: https://github.com/dsc-project-mr/mr-fe-internal/pull/44/files#diff-e091c326cab0be9547c7d7faea684d57dc80678afe2a870e62f15401135406d1

2023-02-15 14:54 UTC, wilinetan approved these changes
@lihuicham I helped to fix the issues mentioned above already. once you are ready can merge. thanks!

2023-03-15 07:39 UTC, merged